services:
  postgresql: # Use service name (postgresql) as the host name in pgadmin
    image: docker.io/bitnami/postgresql:16
    container_name: postgresql # What the container will be named hereafter
    volumes:
      - postgresql_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_DATABASE=kaupunginperhoset
      - POSTGRESQL_USERNAME=havununna
      - POSTGRESQL_PASSWORD=havununna
    ports:
      - 5432:5432
  redis:
    image: docker.io/bitnami/redis:7.0
    volumes:
      - redis_data:/bitnami
    environment:
      - ALLOW_EMPTY_PASSWORD=yes # Only in development
  airflow-scheduler:
    image: docker.io/bitnami/airflow-scheduler:2
    environment:
      - AIRFLOW_DATABASE_NAME=kaupunginperhoset
      - AIRFLOW_DATABASE_USERNAME=havununna
      - AIRFLOW_DATABASE_PASSWORD=havununna
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_WEBSERVER_HOST=airflow
  airflow-worker:
    image: docker.io/bitnami/airflow-worker:2
    environment:
      - AIRFLOW_DATABASE_NAME=kaupunginperhoset
      - AIRFLOW_DATABASE_USERNAME=havununna
      - AIRFLOW_DATABASE_PASSWORD=havununna
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_WEBSERVER_HOST=airflow
  airflow:
    image: docker.io/bitnami/airflow:2
    environment:
      - AIRFLOW_DATABASE_NAME=kaupunginperhoset
      - AIRFLOW_DATABASE_USERNAME=havununna
      - AIRFLOW_DATABASE_PASSWORD=havununna
      - AIRFLOW_USERNAME=heinanorsu
      - AIRFLOW_PASSWORD=heinanorsu
      - AIRFLOW_EXECUTOR=CeleryExecutor
    ports:
      - '8080:8080'
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: havununna@havununna.com
      PGADMIN_DEFAULT_PASSWORD: havununna
    ports:
      - 5050:80
volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
